### ISSUE TITLE
Just can't get started

### ISSUE THREAD

**Issue by uyouthe** [grommet/grommet-cli#35]
Hello. Grommet looks awesome and I can't wait to check it out, but when I go _exactly_ like [tutorial](https://grommet.github.io/docs/get-started) asks me to go, I get
`(node:1528) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 1): Error: 0`, right on `grommet new sample-app`

I get the error on Windows, NPM 3.10.10 and Node 6.9.4.

**Comment by alansouzati** [comment]
interesting. are you running with administrator permission? I'm assuming for some reason your CLI is not able to create the folder.

I cannot reproduce this issue in my mac. let me try to reproduce it in a windows machine.

**Comment by uyouthe** [comment]
Yes, of course I run as administrator. If there was any Grommet updates since then, the bug may be fixed, but 23 days ago I got that error on latest version then and I'm sure I did everything just as described in tutorial.

Thanks for your support!

**Comment by alansouzati** [comment]
i'm setting up a windows vm right now so that I can try this.

**Comment by alansouzati** [comment]
I was able to "reproduce" this, but it is just a warning, the app should work as expect.

<img width="1337" alt="screen shot 2017-06-26 at 2 40 17 pm" src="https://user-images.githubusercontent.com/1207250/27561570-85e84ab8-5a7d-11e7-91a1-8bd0c9e81b27.png">

This is related to an **optional** node fsevents module. It is only supported on windows if you have the Windows SDK.

I will make sure to remove the unhandledpromise warning in the CLI so that it does not confuse folks.

FYI we do not use fsevents directly but webpack-dev-server does. See this issue for more information:

https://github.com/strongloop/fsevents/issues/165

**Comment by alansouzati** [comment]
the unhandled promise has been removed in this commit:

https://github.com/grommet/grommet-cli/commit/b7f13150685cebf22d1dab6150d5b1dfa123c77a

**Comment by uyouthe** [comment]
Thanks a lot!
