### ISSUE TITLE
Docs for grommet-cli and dxc theme

### ISSUE THREAD

**Issue by kavink** [grommet/grommet-cli#45]
Wondering if there are docs for grommet-cli and how it works, i.e. does it use create-react-app underneath ? Also trying to create new app dxc theme is missing.

**Comment by alansouzati** [comment]
Hi, I believe DXC theme is not part of an official release yet. We will release a new version soon (probably this friday).

The best source of documentation for the cli is `grommet help` command, you can also issue help command for a specific task, for example `grommet new --help`.

It does not use create-react-app underneath.

I'm closing this issue since I believe there is nothing to be fixed. Feel free to continue the discussion here.
